In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../data/processed_moviesdrama.csv')

In [12]:
df[df["genre"].str.contains("youth", case=False)]

,id,title,native-title,genre,director,format,type,country,release_date,duration,...,duration (min),release_year,rate_num,score,user_count,rating_norm,actor,combined_emb,combined_tf,poster
1,739603,Twinkling Watermelon,반짝이는 워터멜론,"Romance, Youth, Drama, Fantasy",Son Jung Hyun,Standard Series,Drama,South Korea,"Sep 25, 2023",1 hr. 10 min.,...,70,2023,15,9.2,103873,0.92,"Ryeo Un, Choi Hyun Wook, Seol In Ah, Shin Eun ...","Twinkling Watermelon Romance, Youth, Drama, Fa...",twinkling watermelon romance youth drama fanta...,https://i.mydramalist.com/2w44jE_4c.jpg?v=1
3,702267,Weak Hero Class 1,약한영웅 Class 1,"Action, Youth, Drama",Park Dhan Hee,Standard Series,Drama,South Korea,"Nov 18, 2022",40 min.,...,40,2022,18,9.1,114265,0.91,"Park Ji Hoon, Choi Hyun Wook, Hong Kyung, Kim ...","Weak Hero Class 1 Action, Youth, Drama Action,...",weak hero class 1 action youth drama action yo...,https://i.mydramalist.com/pq2lr_4c.jpg?v=1
8,13544,Reply 1988,응답하라 1988,"Comedy, Romance, Life, Youth","Shin Won Ho, Yoo Hak Chan",Standard Series,Drama,South Korea,"Nov 6, 2015",1 hr. 35 min.,...,95,2015,15,9.0,69560,0.90,"Lee Hye Ri, Go Kyung Pyo, Ryu Jun Yeol, Park B...","Reply 1988 Comedy, Romance, Life, Youth Comedy...",reply 1988 comedy romance life youth comedy ro...,https://i.mydramalist.com/EVe0p_4c.jpg?v=1
29,752799,Study Group,스터디그룹,"Action, Thriller, Comedy, Youth",Lee Jang Hoon,Standard Series,Drama,South Korea,"Jan 23, 2025",42 min.,...,42,2025,18,8.9,51270,0.89,"Hwang Min Hyun, Han Ji Eun, Cha Woo Min, Lee J...","Study Group Action, Thriller, Comedy, Youth Ac...",study group action thriller comedy youth actio...,https://i.mydramalist.com/ABRNyg_4c.jpg?v=1
34,702271,Weak Hero Class 2,약한영웅 Class 2,"Action, Thriller, Youth, Drama",Park Dhan Hee,Standard Series,Drama,South Korea,"Apr 25, 2025",43 min.,...,43,2025,18,8.8,59137,0.88,"Park Ji Hoon, Ryeo Un, Choi Min Yeong, Lee Min...","Weak Hero Class 2 Action, Thriller, Youth, Dra...",weak hero class 2 action thriller youth drama ...,https://i.mydramalist.com/73bB8D_4c.jpg?v=1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4815,15490,Sunshine Love,션샤인 러브,"Romance, Youth, Drama",NaN,Feature Film,Movie,South Korea,"Sep 17, 2015",1 hr. 19 min.,...,79,2015,0,6.1,18,0.61,"Oh Jung Se, Jo Eun Ji, Lee Mi Do, Park Sang Gy...","Sunshine Love Romance, Youth, Drama Romance, Y...",sunshine love romance youth drama romance yout...,https://i.mydramalist.com/lWB8Qc.jpg?v=1
4849,33831,Arousers,어라우저: 각성자들,"Mystery, Youth, Drama, Supernatural",NaN,Feature Film,Movie,South Korea,"Jun 22, 2015",1 hr. 7 min.,...,67,2015,0,0.0,0,0.00,"Lee Paul, Lee Ji Hye, Lee Young Ho","Arousers Mystery, Youth, Drama, Supernatural M...",arousers mystery youth drama supernatural myst...,https://i.mydramalist.com/JK2Blc.jpg?v=1
4864,13998,Makgeolli Girls,막걸스,"Business, Comedy, Youth",NaN,Feature Film,Movie,South Korea,"May 21, 2015",1 hr. 50 min.,...,110,2015,15,7.0,19,0.70,"Hong Ah Reum, Changjo, Kim Min Young, Jung Min...","Makgeolli Girls Business, Comedy, Youth Busine...",makgeolli girls business comedy youth business...,https://i.mydramalist.com/m08okc.jpg?v=1
4878,9743,Twenty,스물,"Comedy, Romance, Youth",NaN,Feature Film,Movie,South Korea,"Mar 25, 2015",1 hr. 55 min.,...,115,2015,15,8.0,16298,0.80,"Kim Woo Bin, Lee Jun Ho, Kang Ha Neul, Jung So...","Twenty Comedy, Romance, Youth Comedy, Romance,...",twenty comedy romance youth comedy romance you...,https://i.mydramalist.com/6vA8Kc.jpg?v=1
4904,700459,Plughole,하수구,"Youth, Drama",NaN,Feature Film,Movie,South Korea,"Jan 1, 2015",35 min.,...,35,2015,18,6.3,6,0.63,-,"Plughole Youth, Drama Youth, Drama Short Film,...",plughole youth drama youth drama short film sc...,https://i.mydramalist.com/Bn6r7_4c.jpg?v=1

In [5]:
genre_counts = (
    df['genre']
    .str.split(',')       # Step A: Split the strings into lists
    .explode()            # Step B: Transform each list item into its own row
    .str.strip()          # Step C: Clean up any extra spaces (e.g., " Life" -> "Life")
    .value_counts()       # Step D: Count the occurrences of each individual genre
)

print(genre_counts)

genre
Drama            2497
Romance          2299
Comedy           1500
Mystery           789
Thriller          739
Youth             634
Life              613
Melodrama         527
Action            517
Fantasy           360
Family            324
Supernatural      295
Crime             291
Historical        258
Horror            214
Music             184
Business          159
Sci-Fi            148
Psychological     143
Documentary       142
Political         118
Law               104
Sports             96
Medical            91
Food               88
Sitcom             67
Adventure          65
Military           42
                   42
War                30
Martial Arts       18
Tokusatsu           8
Mature              6
Name: count, dtype: int64

In [31]:
subset= df.iloc[0:50]
print(subset.shape[0])
genre = ["thriller", "action"]
genre_mask = subset["genre"].dropna().apply(
    lambda row_text: any(g.lower() in row_text.lower() for g in genre))
subset = subset[genre_mask]
subset.sort_values(by="release_year", ascending=False, inplace=True)
subset

50

,id,title,native-title,genre,director,format,type,country,release_date,duration,...,duration (min),release_year,rate_num,score,user_count,rating_norm,actor,combined_emb,combined_tf,poster
5,54697,The Trauma Code: Heroes on Call,중증외상센터,"Action, Comedy, Drama, Medical",Lee Do Yoon,Standard Series,Drama,South Korea,"Jan 24, 2025",51 min.,...,51,2025,15,9.1,54819,0.91,"Ju Ji Hoon, Choo Young Woo, Ha Young, Yoon Kyu...","The Trauma Code: Heroes on Call Action, Comedy...",the trauma code heroes on call action comedy d...,https://i.mydramalist.com/735qBe_4c.jpg?v=1
29,752799,Study Group,스터디그룹,"Action, Thriller, Comedy, Youth",Lee Jang Hoon,Standard Series,Drama,South Korea,"Jan 23, 2025",42 min.,...,42,2025,18,8.9,51270,0.89,"Hwang Min Hyun, Han Ji Eun, Cha Woo Min, Lee J...","Study Group Action, Thriller, Comedy, Youth Ac...",study group action thriller comedy youth actio...,https://i.mydramalist.com/ABRNyg_4c.jpg?v=1
34,702271,Weak Hero Class 2,약한영웅 Class 2,"Action, Thriller, Youth, Drama",Park Dhan Hee,Standard Series,Drama,South Korea,"Apr 25, 2025",43 min.,...,43,2025,18,8.8,59137,0.88,"Park Ji Hoon, Ryeo Un, Choi Min Yeong, Lee Min...","Weak Hero Class 2 Action, Thriller, Youth, Dra...",weak hero class 2 action thriller youth drama ...,https://i.mydramalist.com/73bB8D_4c.jpg?v=1
36,761313,Death's Game Part 2,"이재, 곧 죽습니다 파트2","Thriller, Drama, Fantasy",NaN,Standard Series,Drama,South Korea,"Jan 5, 2024",55 min.,...,55,2024,18,8.8,41720,0.88,"Seo In Guk, Park So Dam, Nam Kyung Eup, Go You...","Death's Game Part 2 Thriller, Drama, Fantasy T...",death s game part 2 thriller drama fantasy thr...,https://i.mydramalist.com/XdwWLn_4c.jpg?v=1
21,705589,Taxi Driver Season 2,모범택시 시즌2,"Action, Thriller, Mystery, Crime","Lee Dan, Jang Yeong Seok",Standard Series,Drama,South Korea,"Feb 17, 2023",1 hr. 10 min.,...,70,2023,18,8.9,28466,0.89,"Lee Je Hoon, Kim Eui Sung, Pyo Ye Jin, Jang Hy...","Taxi Driver Season 2 Action, Thriller, Mystery...",taxi driver season 2 action thriller mystery c...,https://i.mydramalist.com/2wr8zR_4c.jpg?v=1
9,25560,Moving,무빙,"Action, Thriller, Mystery, Supernatural",Park In Je,Standard Series,Drama,South Korea,"Aug 9, 2023",47 min.,...,47,2023,18,9.0,54642,0.90,"Ryu Seung Ryong, Han Hyo Joo, Zo In Sung, Cha ...","Moving Action, Thriller, Mystery, Supernatural...",moving action thriller mystery supernatural ac...,https://i.mydramalist.com/l0YBOx_4c.jpg?v=1
15,745581,The Glory Part 2,더글로리 파트 2,"Thriller, Drama, Melodrama",Ahn Gil Ho,Standard Series,Drama,South Korea,"Mar 10, 2023",55 min.,...,55,2023,18,8.9,83049,0.89,"Song Hye Kyo, Lee Do Hyun, Im Ji Yeon, Yeom Hy...","The Glory Part 2 Thriller, Drama, Melodrama Th...",the glory part 2 thriller drama melodrama thri...,https://i.mydramalist.com/vXjLPq_4c.jpg?v=1
40,733445,Death's Game,"이재, 곧 죽습니다","Thriller, Drama, Fantasy",NaN,Standard Series,Drama,South Korea,"Dec 15, 2023",55 min.,...,55,2023,18,8.8,53156,0.88,"Seo In Guk, Park So Dam, Go Youn Jung, Nam Kyu...","Death's Game Thriller, Drama, Fantasy Thriller...",death s game thriller drama fantasy thriller d...,https://i.mydramalist.com/QJKVK7_4c.jpg?v=1
3,702267,Weak Hero Class 1,약한영웅 Class 1,"Action, Youth, Drama",Park Dhan Hee,Standard Series,Drama,South Korea,"Nov 18, 2022",40 min.,...,40,2022,18,9.1,114265,0.91,"Park Ji Hoon, Choi Hyun Wook, Hong Kyung, Kim ...","Weak Hero Class 1 Action, Youth, Drama Action,...",weak hero class 1 action youth drama action yo...,https://i.mydramalist.com/pq2lr_4c.jpg?v=1
37,695963,Tomorrow,내일,"Action, Thriller, Drama, Fantasy","Kim Tae Yoon, Sung Chi Wook",Standard Series,Drama,South Korea,"Apr 1, 2022",60 min.,...,60,2022,15,8.8,69331,0.88,"Kim Hee Sun, Ro Woon, Lee Soo Hyuk, Yun Ji On,...","Tomorrow Action, Thriller, Drama, Fantasy Acti...",tomorrow action thriller drama fantasy action ...,https://i.mydramalist.com/qjBQ2_4c.jpg?v=1
4,52939,Alchemy of Souls,환혼,"Action, Historical, Romance, Fantasy",Park Joon Hwa,Standard Series,Drama,South Korea,"Jun 18, 2022",1 hr. 20 min.,...,80,2022,15,9.1,108485,0.91,"Lee Jae Wook, Jung So Min, Hwang Min Hyun, Shi...","Alchemy of Souls Action, Historical, Romance, ...",alchemy of souls action historical romance fan...,https://i.mydramalist.com/Beg4z_4c.jpg?v=1
20,733261,Alchemy of Souls Season 2: Light and Shadow,환혼 시즌2: 빛과 그림자,"Action, Historical, Romance, Fantasy","Park Joon Hwa, Bae Hyun Jin",Standard Series,Drama,South Korea,"Dec 10, 2022",1 hr. 21 min.,...,81,2022,15,8.9,73527,0.89,"Lee Jae Wook, Go Youn Jung, Hwang Min Hyun, Sh...",Alchemy of Souls Season 2: Light and Shadow Ac...,alchemy of souls season 2 light and shadow act...,https://i.mydramalist.com/X06Rd_4c.jpg?v=1
24,685237,The Glory,더 글로리,"Thriller, Drama, Melodrama",Ahn Gil Ho,Standard Series,Drama,South Korea,"Dec 30, 2022",50 min.,...,50,2022,18,8.9,111342,0.89,"Song Hye Kyo, Lee Do Hyun, Im Ji Yeon, Yeom Hy...","The Glory Thriller, Drama, Melodrama Thriller,...",the glory thriller drama melodrama thriller dr...,https://i.mydramalist.com/4v6zJ_4c.jpg?v=1
38,52921,Taxi Driver,모범택시,"Action, Thriller, Crime, Drama",Park Joon Woo,Standard Series,Drama,South Korea,"Apr 9, 2021",1 hr. 5 min.,...,65,2021,18,8.8,52657,0.88,"Lee Je Hoon, Esom, Kim Eui Sung, Pyo Ye Jin, J...","Taxi Driver Action, Thriller, Crime, Drama Act...",taxi driver action thriller crime drama action...,https://i.mydramalist.com/2Bkww_4c.jpg?v=1
48,59001,D.P.,디피,"Action, Military, Drama",NaN,Standard Series,Drama,South Korea,"Aug 27, 2021",50 min.,...,50,2021,15,8.8,46564,0.88,"Jung Hae In, Koo Kyo Hwan, Kim Sung Kyun, Son ...","D.P. Action, Military, Drama Action, Military,...",d p action military drama action military dram...,https://i.mydramalist.com/XkYln_4c.jpg?v=1
27,58953,Mouse,마우스,"Thriller, Mystery, Psychological","Choi Joon Bae, Kang Cheol Woo",Standard Series,Drama,South Korea,"Mar 3, 2021",1 hr. 15 min.,...,75,2021,18,8.9,41993,0.89,"Lee Seung Gi, Lee Hee Joon, Park Ju Hyun, Gyeo...","Mouse Thriller, Mystery, Psychological Thrille...",mouse thriller mystery psychological thriller ...,https://i.mydramalist.com/XNeKO_4c.jpg?v=1
35,690709,Happiness,해피니스,"Action, Thriller, Drama, Sci-Fi",Ahn Gil Ho,Standard Series,Drama,South Korea,"Nov 5, 2021",1 hr. 5 min.,...,65,2021,15,8.8,77720,0.88,"Han Hyo Joo, Park Hyung Sik, Jo Woo Jin, Lee J...","Happiness Action, Thriller, Drama, Sci-Fi Acti...",happiness action thriller drama sci fi action ...,https://i.mydramalist.com/BWXjV_4c.jpg?v=1
7,54625,Flower of Evil,악의 꽃,"Thriller, Romance, Crime, Melodrama","Kim Chul Gyu, Yoon Jong Ho",Standard Series,Drama,South Korea,"Jul 29, 2020",1 hr. 10 min.,...,70,2020,15,9.0,94312,0.90,"Lee Joon Gi, Moon Chae Won, Jang Hee Jin, Seo ...","Flower of Evil Thriller, Romance, Crime, Melod...",flower of evil thriller romance crime melodram...,https://i.mydramalist.com/WAEAp_4c.jpg?v=1
41,62085,The Uncanny Counter,경이로운 소문,"Action, Mystery, Drama, Supernatural",Park Bong Sub,Standard Series,Drama,South Korea,"Nov 28, 2020",1 hr. 10 min.,...,70,2020,15,8.8,76822,0.88,"Cho Byeong Kyu, Yoo Joon Sang, Kim Se Jeong, Y...","The Uncanny Counter Action, Mystery, Drama, Su...",the uncanny counter action mystery drama super...,https://i.mydramalist.com/v3032_4c.jpg?v=1
30,32220,Kingdom Season 2,킹덤 시즌 2,"Thriller, Historical, Horror, Supernatural","Kim Sung Hoon, Park In Je",Standard Series,Drama,South Korea,"Mar 13, 2020",45 min.,...,45,2020,18,8.9,37527,0.89,"Ju Ji Hoon, Bae Doo Na, Kim Sung Kyu, Ryu Seun...","Kingdom Season 2 Thriller, Historical, Horror,...",kingdom season 2 thriller historical horror su...,https://i.mydramalist.com/mOnjAk_4c.jpg?v=1
46,22806,Kingdom,킹덤,"Thriller, Historical, Horror, Political",Kim Sung Hoon,Standard Series,Drama,South Korea,"Jan 25, 2019",51 min.,...,51,2019,18,8.8,50785,0.88,"Ju Ji Hoon, Ryu Seung Ryong, Bae Doo Na, Kim S...","Kingdom Thriller, Historical, Horror, Politica...",kingdom thriller historical horror political t...,https://i.mydramalist.com/d4d1Wc.jpg?v=1
19,21308,Mother,마더,"Thriller, Mystery, Psychological, Melodrama","Kim Chul Gyu, Yoon Hyun Gi",Standard Series,Drama,South Korea,"Jan 24, 2018",1 hr. 3 min.,...,63,2018,15,8.9,11244,0.89,"Lee Bo Young, Heo Yool, Lee Hye Young, Go Sung...","Mother Thriller, Mystery, Psychological, Melod...",mother thriller mystery psychological melodram...,https://i.mydramalist.com/dRPqdc.jpg?v=1
31,13239,Signal,시그널,"Thriller, Mystery, Sci-Fi",Kim Won Suk,Standard Series,Drama,South Korea,"Jan 22, 2016",1 hr. 15 min.,...,75,2016,15,8.8,42676,0.88,"Lee Je Hoon, Kim Hye Soo, Jo Jin Woong, Kim Wo...","Signal Thriller, Mystery, Sci-Fi Thriller, Mys...",signal thriller mystery sci fi thriller myster...,https://i.mydramalist.com/6wYZO_4c.jpg?v=1
44,10814,Healer,힐러,"Action, Thriller, Mystery, Romance","Lee Jeong Seop, Kim Jin U",Standard Series,Drama,South Korea,"Dec 8, 2014",60 min.,...,60,2014,15,8.8,90560,0.88,"Ji Chang Wook, Park Min Young, Yoo Ji Tae, Kim...","Healer Action, Thriller, Mystery, Romance Acti...",healer action thriller mystery romance action ...,https://i.mydramalist.com/lBOo4c.jpg?v=1

In [12]:
def load_data():
    df = pd.read_csv('src/data/processed_moviesdrama.csv')
    df["release_year"] = pd.to_numeric(df["release_year"], errors="coerce")
    df["score"] = pd.to_numeric(df["score"], errors="coerce")
    df["id"] = df["id"].astype(str)  # keep id as string for consistency
    df["primary_genre"] = (df['genre'].str.split(",").str[0].str.strip())

    # new dataframe for searching purpose
    drama = df[df["type"] == "Drama"].copy()
    movie = df[df["type"] == "Movie"].copy()
    return df, drama, movie

In [14]:
df, _, _ = load_data()

In [ ]:
## Spotlight

new_release = df[df['release_year' >= 2026]]
todays_pick = df[(df["score"]>7) & (df["release_year"] >= 2025)]
top_rated = df[(df["score"] >= 8.5) & (df["user_count"] > 1000)]
most_popular = df[df["user_count"] >= 30000]

In [21]:
df["release_year"].unique()

array([2025, 2023, 2021, 2022, 2020, 2015, 2019, 2024, 2018, 2017, 2016,
       2014, 2026, 2013, 2012, 2010, 2011, 2009])

In [17]:
COLLECTIONS = [
    {
        "key": "politic_power", "label": "Politic & Power Struggle",
        "rules": {
            "genres": ["political"],
            "score": 6,
            "year": 2015,
            "user_count": 5000
        }},
    {
        "key": "webtoon", "label": "From Page to Screen",
        "rules": {
            "tag": ["webtoon", "novel"],
            "score": 6,
            "user_count": 5000
        }},
    {
        "key": "horror", "label": "Horror",
        "rules": {
            "genres": ["horror", "supernatural"],
            "score": 7,
            "user_count": 5000
        }
    },
    {
        "key": "pyschological", "label": "Pyschological & Mind Bending",
        "rules": {
            "genres": ["psychological", "law"],
            "score": 6,
            "user_count": 5000
        }
    },
    {
        "key": "thriler", "label": "Suspenseful Thriller & Action",
        "rules": {
            "genres": ["thriller", "action", "crime"],
            "score": 6,
            "user_count": 5000
        }
    },
    {
        "key": "youth_life", "label": "The Freshness of Youth & Life",
        "rules": {
            "genres": ["life", "youth"],
            "score": 6,
            "user_count": 5000
        }
    },
    {
        "key": "easy_comedy", "label": "Your Next Binge  List",
        "rules": {
            "genres": ["comedy"],
            "score": 6,
            "user_count": 5000
        }
    },
]

In [18]:
import random
rotation = random.sample(COLLECTIONS, k=min(2, len(COLLECTIONS)))
rotation

[{'key': 'youth_life',
  'label': 'The Freshness of Youth & Life',
  'rules': {'genres': ['life', 'youth'], 'score': 6, 'user_count': 5000}},
 {'key': 'webtoon',
  'label': 'From Page to Screen',
  'rules': {'tag': ['webtoon', 'novel'], 'score': 6, 'user_count': 5000}}]